#!/usr/bin/env ts-node

// This is a dummy entrypoint, specifically written so that it
// adds "--harmony" when running the node script, because I
// wanted to use weird ES6 stuff, but didnt want to transpile

// Create a process spawner
// const spawn = require('child_process').spawn;


//     var childProcess = require("child_process");
//     var oldSpawn = childProcess.spawn;
//     function mySpawn() {
//         console.log('spawn called');
//         console.log(arguments);
//         var result = oldSpawn.apply(this, arguments);
//         return result;
//     }
//     childProcess.spawn = mySpawn;
// const spawn = childProcess.spawn;

var spawn = require('cross-spawn');

// Compile a list of args
// Find the current path, append the real entrypoint name
// Drop the first 2 args (these are current file path and... something else, I forget)
var args = [ __dirname + '/nwsh.ts' ].concat(process.argv.slice(2));

// For some reason, it keeps switching the command to be 'node'...
// Let's un-do that, then run it.
process.argv[0] = 'ts-node';
spawn(process.argv[0], [].concat(args), { stdio: [0, 1, 2] });
